### ISSUE TITLE
Source and Transform Nodes (undefined undefined)

### ISSUE THREAD

**Issue by tpiros** [cloudinary-devs/gatsby-transformer-cloudinary#17] opened 2019-11-19 11:06 UTC
I am trying to use this transformer, however I have run into this issue:

```
success initialize cache - 0.020s
success copy gatsby files - 0.046s
success onPreBootstrap - 0.005s

 ERROR 

undefined undefined
  Error: 
not finished source and transform nodes - 61.578s
```

This is how my `gatsby-config` looks like:

```javascript
require('dotenv').config({
  path: `.env.development`,
});

module.exports = {
  siteMetadata: {
    title: `ChristMart`,
    description: `ChristMart - Your Favourite Online Christmas Store`,
    author: `Tamas Piros`,
    company: `Full Stack Training Ltd`,
    companyWebsite: `https://fullstacktraining.com`
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `content`,
        path: `${__dirname}/src/content`,
      },
    },
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`./src/components/layout`),
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: 'gatsby-transformer-cloudinary',
      options: {
        cloudName: process.env.CLOUDINARY_CLOUD_NAME,
        apiKey: process.env.CLOUDINARY_API_KEY,
        apiSecret: process.env.CLOUDINARY_API_SECRET,
        uploadFolder: 'gatsby-cloudinary',
      },
    },
    `gatsby-plugin-postcss`,
    {
      resolve: 'gatsby-plugin-purgecss',
      options: {
        tailwind: true,
        purgeOnly: ['src/css/style.css', 'src/css/global.css'],
      },
    },
  ],
}
```

I can also confirm that I have the right cloudname, apikey and secret setup.

Any suggestions why this error is happening?

**Comment by tpiros** [comment] 2019-11-20 06:59
I think I managed to pinpoint the issue - it seems that if I have a bunch of larger image files, the build process just errors. In the above case I had 4-5 jpgs (~3-4 MB each) that broke the process.

**Comment by Chuloo** [comment] 2019-12-24 23:30
Thanks for pointing this out @tpiros. If I get you correctly this means the plugin breaks when larger files are to be handled?

**Comment by rheinardkorf** [comment] 2020-01-09 23:29
I had a similar issue. Like @tpiros , yes, seems to be with larger assets.

**Comment by tpiros** [comment] 2020-01-28 13:20
@Chuloo - do you have any updates on this issue or #11 ?

**Comment by ovsw** [comment] 2020-01-31 12:09
same issue, but happens with even normal-sized images. At least I think so, I don't consider something under 1MB to be large for the original version of an image.

**Comment by Chuloo** [comment] 2020-02-02 20:31
This issue is fixed by #21, and will be closed. Please re-open if you face the same issue again.

**Comment by Epotignano** [comment] 2020-03-16 23:56
Hello everybody, I'm facing the same issue when trying to build a site with +60 images

**Comment by Chuloo** [comment] 2020-03-17 12:46
HI, @Epotignano did you try adjusting your responsive breakpoints? Did you set any at all? How can I reproduce this?

**Closed** 2020-03-17 12:46 UTC
Labels: bug
