### ISSUE TITLE
childCloudinaryAsset undefined

### ISSUE THREAD

**Issue by davidpanzarella** [cloudinary-devs/gatsby-transformer-cloudinary#42] opened 2020-07-30 04:56 UTC
I'm having some issues with the default examples shown. I have no issues getting my files uploaded, and querying them using what's in GraphiQL, but when I try to use the example I see this:

![image](https://user-images.githubusercontent.com/755283/88743355-503f9600-d0f9-11ea-80a7-cd782312ee4f.png)
![image](https://user-images.githubusercontent.com/755283/88745067-f55c6d80-d0fd-11ea-8a25-306fbdbfae31.png)
![image](https://user-images.githubusercontent.com/755283/88745057-f097b980-d0fd-11ea-9a32-1d2efe522e7f.png)

Have there been some changes since you published this?

**Comment by kurttomlinson** [comment] 2020-08-01 04:19
That's really strange that it suggested `childrenCloudinaryAsset` instead of `childCloudinaryAsset`. `childrenCloudinaryAsset` isn't mentioned anywhere in the source of `gatsby-transformer-cloudinary`. I'm assuming you're using `gatsby-source-filesystem` to pick out your images and upload them to Cloudinary?

Which version of `gatsby-transformer-cloudinary` are you running?

This doesn't solve your problem, but I'm 90% sure that fragments don't work in GraphiQL. (They work fine in your Gatsby app, but GraphiQL doesn't load them. It's an [open issue](https://github.com/gatsbyjs/gatsby/issues/14371), I think.)

I was able to get a similar query to work fine on a dummy app with version 1.0.1:

![image](https://user-images.githubusercontent.com/1914753/89093892-2356e180-d38c-11ea-8e80-e325873f3626.png)

**Comment by davidpanzarella** [comment] 2020-08-12 03:59
Thanks for the quick reply @kurttomlinson. Sorry, it's taken a bit for me to get back to you.

The current version is `"gatsby-transformer-cloudinary": "1.0.1"`, and yes I use `gatsby-source-filesystem` without any issues on the upload to Cloudinary. I'll test again without `children` and let you know if it changes at all.

**Comment by thatjimmy** [comment] 2020-09-23 09:06
Chiming in, I had the same issue today. I was previously using version 0.3.5. I just updated the plugin to version 1.0.1 and gave it a spin. Otherwise the graphql page queries in the page files remained the same. When I tried to start up the dev server I got similar errors, but my images uploaded just fine.

```
ERROR #85923  GRAPHQL
There was an error in your GraphQL query:
Cannot query field "childCloudinaryAsset" on type "File".
```
And
```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
.../src/pages/page.js
242:11  error  Cannot query field "childCloudinaryAsset" on type "File". Did you mean "childrenCloudinaryAsset"?  graphql/template-strings
✖ 1 problem (1 error, 0 warnings)
```

<img width="1058" alt="Screen Shot 2020-09-23 at 16 56 21" src="https://user-images.githubusercontent.com/55338674/93983944-284d7580-fdbe-11ea-9c46-d80dbac853a2.png">

I updated the page queries to have `childrenCloudinaryAsset` and the errors were resolved. But...

`childrenCloudinaryAsset` seems to be returning an array with the first item being the **fluid** object, compared to `childImageSharp` which returns an object directly.

GraphiQL Query:
```
query MyQuery {
  allFile {
    nodes {
      childrenCloudinaryAsset {
        fluid {
          src
        }
      }
      childImageSharp {
        fluid {
          src
        }
      }
    }
  }
}
```

And results:
```
...
        {
          "childrenCloudinaryAsset": [ # An array
            {
              "fluid": {
                "src": "https://res.cloudinary.com/myaccount/image/upload/f_auto,q_auto/v1600846437/myfolder/image"
              }
            }
          ],
          "childImageSharp": { # An object
            "fluid": {
              "src": "/static/3995697a21882d875219185954ab3416/630fb/image.png"
            }
          }
        },
```
This caused some errors and images did not load until it was dealt with.

**Comment by kurttomlinson** [comment] 2020-09-24 03:02
Thanks for the new information. I've been able to reproduce this. I think this is a problem caused by two images having the same file name.

As a workaround, try making sure that each image on your site has a unique file name.

I'm looking into a way to fix this.

**Comment by kurttomlinson** [comment] 2020-09-24 03:41
I believe this should be fixed by https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/pull/50.

**Comment by thatjimmy** [comment] 2020-09-24 07:56
Awesome, thanks. I did have 2 files with the same name in separate subfolders.

**Comment by Chuloo** [comment] 2020-09-27 12:04
Released with #50, thanks @thatjimmy @kurttomlinson & @davidpanzarella 👍

**Closed by Chuloo** 2020-09-27 12:04 UTC
Labels: needs more info

**Comment by ludusrusso** [comment] 2020-11-14 15:07
I had this same issue (after #50) caused by two images with same name but different extension in same folder :D

It could be useful to add also the extension to the assets id here?

https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/blob/c2f2a8c2ed778c4b382be6523e6f8ecccc7d5170/packages/gatsby-transformer-cloudinary/upload.js#L96-L100

**Comment by kurttomlinson** [comment] 2020-11-14 16:25
@ludusrusso That might work, but I'm not sure it's a great idea. I think Cloudinary builds public IDs from filenames without the extension. I think you might end up with one file clobbering the other on Cloudinary if you do that. I'm not sure, but that's my first thought.

The reason I think Cloudinary doesn't include extensions in the public ID is because you can upload a png, and then download that same image from Cloudinary with a .jpg extension and Cloudinary will automatically convert the image format for you.

**Comment by ludusrusso** [comment] 2020-11-14 16:39
@kurttomlinson thanks for the reply. I'm not sure too this is a good idea (this is why I asked before submit a pull request). 👍
