### ISSUE TITLE
How & Where to create Nodes so that coverPhoto is transformed into the CloudinaryAsset Type?

### ISSUE THREAD

**Issue by johncarpenter67** [cloudinary-devs/gatsby-transformer-cloudinary#61] opened 2020-11-22 18:31 UTC
Trying to figure out how to create nodes for assets that are already on cloudinary? So far, I have tried to create these nodes in `gatsby-node.js` like so:

```
exports.sourceNodes = ({
  actions: { createNode },
  createNodeId,
  createContentDigest,
}) => {
  return avengers.map((avenger) =>
    createNode({
      ...avenger,
      id: createNodeId(avenger.name),
      internal: {
        type: `Avenger`,
        contentDigest: createContentDigest(avenger),
      },
      title: 'Some Title,
      publishedAt: '2020-11-12',
      coverPhoto: { //just some static data in here for now for testing purposes
        cloudinaryAssetData: true,
        cloudName: 'mycloudname',
        publicId: 'myfolder/someimage.png',
        originalHeight: 2048,
        originalWidth: 2048,
      },
    })
  )
}
```

In the docs it says:

> The coverPhoto property in the node above will be deleted and replaced by gatsby-transformer-cloudinary with a CloudinaryAsset node that can be used with gatsby-image

However, in graphql it still shows me `coverPhoto` and all its properties. and does not replace it with `CloudinaryAsset`, which I would've expected. Is the order in which the gatsby-node file run before the transformer plugin maybe? 

How can I create the image nodes in a way so that `gatsby-transformer-cloudinary` can do its magic?

**Comment by kurttomlinson** [comment] 2020-11-24 01:42
@johncarpenter67 That looks like it should work to me. Do you have a small project that reproduces this issue that you could share?

**Comment by Chuloo** [comment] 2021-01-04 08:36
Closing this out now as there hasn't been any follow-up. Please feel free to comment if the issue still exists 🙏

**Closed by Chuloo** 2021-01-04 08:36 UTC
Labels: needs more info
